name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Установка Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Установка зависимостей
      run: npm install

    - name: Линтинг кода
      run: npm run lint

    - name: Запуск тестов
      run: npm test

    - name: Сборка приложения
      run: npm run build

    - name: Загрузка артефактов сборки
      uses: actions/upload-artifact@v4
      with:
        name: production-build
        path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'

    steps:
    - name: Загрузка артефактов сборки
      uses: actions/download-artifact@v4
      with:
        name: production-build
        path: build/
